baseurl = "https://manishraj.dev/blog/"
languageCode = "en-us"
title = "Blog"
theme = "blog-theme"
author = "Manish Raj"
copyright = " "
canonifyurls = true
paginate = 10
publishDir = ".."

googleAnalytics = ""
disqusShortname = ""

pygmentsStyle = "solarized-dark"
pygmentsCodeFences = true

[[menu.main]]
  name = "Home"
  url = "https://manishraj.dev/"

[[menu.main]]
  name = "Posts"
  url = "/post/"

[params]
  scheme = "dark"
  description = ""

[markup.goldmark.renderer]
unsafe= true

languageCode = "en"
googleAnalytics = ""
Paginate = 10
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Manish Raj" # Author full name
authorEmail = "manish_raj@outlook.com" # Author email

[params.assets]
customCSS = ["custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "manishr41883690"
github = "androidfanatic"
email = "manish_raj@out.com"
linkedin = "manish-raj"
facebook = ""
instagram = "geek.manish"
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","linkedin","facebook","twitter","instagram","email","codepen"]

[params.matomoAnalytics]
siteID = 1
rootURL = ""

[params.fathomAnalytics]
rootURL = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = false