baseurl = "https://manishraj.dev/blog/"
languageCode = "en-us"
title = "Blog"
theme = "blog-theme"
author = "Manish Raj"
copyright = " "
canonifyurls = true
paginate = 10
publishDir = ".."

googleAnalytics = ""
disqusShortname = ""

pygmentsStyle = "solarized-dark"
pygmentsCodeFences = true

[[menu.main]]
  name = "Home"
  url = "https://manishraj.dev/"

[[menu.main]]
  name = "Posts"
  url = "/post/"

[params]
  scheme = "dark"
  description = ""

[markup.goldmark.renderer]
unsafe= true